### ISSUE TITLE
"node-wit": "^2.0.0" uses deprecated API

### ISSUE THREAD

**Issue by vinniebrowne1** [howdyai/botkit-middleware-witai#12]
Hey there,

I noticed an issue where confidence score is not being returned when using botkit-middleware-witai. This is because it is using an old version on node-wit as a dependency. 

Would it be possible to get this updated or is there a work around/something else I should be doing?

var VERSION = "20150306" is now deprecated. The latest is '20160516'

Thanks in advance for everything!

**Comment by vinniebrowne1** [comment]
Looks like theres a PR which may address this actually - Feature new wit #8

**Comment by anonrig** [comment]
node-wit version is updated.
