### ISSUE TITLE
intents are now entities

### ISSUE THREAD

**Issue by jkeefe** [howdyai/botkit-middleware-witai#18]
In the README, you have:

> The results of the call to Wit.ai are added into the incoming message as `message.intents`, and ...

But that should be `message.entities`.

**Comment by peterswimm** [comment]
@jkeefe Thanks for pointing that out, anyone want to take a shot at a PR?

**Comment by michaelmior** [comment]
It seems like all that's needed is a one word change in the README.

**Comment by michaelmior** [comment]
Actually, my mistake. There are other changes needed but I forgot I already made these to my own app. I can send them in a PR.

**Comment by peterswimm** [comment]
@michaelmior care to submit the PR? We will then get NPM updated.

**Comment by michaelmior** [comment]
A PR seems unnecessary for changing one word in the documentation, but sure.

**Comment by peterswimm** [comment]
Thank you!
