### ISSUE TITLE
Bot does not reply 

### ISSUE THREAD

**Issue by abidhkhan** [howdyai/botkit-middleware-witai#22]
Bot failed to reply on message_receive event.  It looks like control never returns to bot controller and it hangs in wit.hears method, getting below log

`debug: Successfully subscribed to Facebook events: {"success":true}
{"msg_id":"262e9aa7-a945-452a-a275-3be9ff7c8970","_text":"hello","outcomes":[{"_text":"hello","confidence":null,"intent":"default_intent","entities":{"contact":[{"confidence":0.5748402256063738,"type":"value","value":"hello","suggested":true}]}}],"WARNING":"DEPRECATED"}
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO 1297127133704505 1297127133704505`

### Code snippet
`module.exports = function(bot, controller){
    var wit = require('botkit-middleware-witai')({
     token: process.env.wit_server_access_token,
     logLevel: 'debug',
     minConfidence: 0,
     });

    //Inject wit in receive
    controller.middleware.receive.use(wit.receive);

    // user said hello
    controller.hears(['hello'], 'direct_message',wit.hears, function(bot, message) {
        bot.botkit.log("Wit.ai detected entities", message.entities);
        bot.reply(message, 'Hey there');

    });

};
`

**Comment by rosy-sanby** [comment]
I am having exactly the same problem. Could you solve it?

**Comment by gcfabri** [comment]
I think you need to change 'direct_message' to 'message_received' for FB bots. But I am facing the same problem here..I need some help too.

**Comment by dhewlettea** [comment]
I'm running into the same problem using with a Slack Bot.

**Comment by NayabSiddiqui** [comment]
I'm running into the same problem. Any update on this issue ?
Thanks in advance.

**Comment by dhewlettea** [comment]
For a Slack bot, I've found this fork to work for everything except direct_message (which also seems to be a bug with the howdyai version): [https://github.com/dfischer/botkit-middleware-witai.git](https://github.com/dfischer/botkit-middleware-witai.git)

**Comment by pilarfc** [comment]
Your bot was sending you a message that this middleware is already deprecated, I think this is why it doesn't work.
